name: github_action
description: A Flutter package demonstrating how to automate publishing to pub.dev using GitHub Actions, with workflows for testing and CI/CD.
version: 0.0.8
homepage: https://github.com/<your-username>/github_action
repository: https://github.com/<your-username>/github_action
issue_tracker: https://github.com/<your-username>/github_action/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# flutter:
# (assets/fonts sections here if you add any later)
