name: Publish to pub.dev

on:
  push:
    tags:
      - "v*" # Run only when you push version tags like v0.0.2
  workflow_dispatch: # Allow manual run from GitHub UI

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Flutter (pinned version for stability)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # ✅ Pin to stable version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test

      # Prepare pub.dev credentials from GitHub Secret
      - name: Prepare pub.dev credentials
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart
          echo "${{ secrets.PUB_CREDENTIALS }}" > $XDG_CONFIG_HOME/dart/pub-credentials.json

      # Do a dry-run publish (sanity check)
      - name: Dry-run publish
        run: flutter pub publish --dry-run

      # Publish only when a version tag is pushed
      - name: Publish to pub.dev
        if: startsWith(github.ref, 'refs/tags/v')
        run: flutter pub publish --force
